server:
  port: 9099
#  servlet:
#    context-path: /sentinel

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:18080
        client-ip: localhost
      eager: true
  application:
    name: simple_sentinel



