server:
  port: 9099

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE

spring:
  application:
    name: simple_sentinel